apiVersion: v1
kind: Service
metadata:
  name: springboot
  labels:
    app: springboot
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: springboot
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: jeetjagasia/wercker-springboot
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
